---
- name: Test custom module
  hosts: localhost
  tasks:
  - name: Run the custom module
    unifi:
      name: "unifi test"
      state: present
    register: testout
  - name: dump test output
    debug:
      msg: "{{ testout }}"
