---
# This is a basic workflow to deploy to local rpi's
name: "Ansible CI/CD"

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the master branch
  push:
    branches: [master, main]
    paths:
      - "ansible_unifi_network/**"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Ensures only 1 workflow is running
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Test the playbooks (YAML) 
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Setup defaults for the steps within a job
    defaults:
      run:
        working-directory: ./ansible_unifi_network

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3

      # Run the playbook against the hosts
      - name: Apply playbook 
        run: ansible-playbook ./*.yaml
