---
# This is a basic workflow to deploy to local rpi's
name: "Ansible Test"

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the master branch
  push:
    branches: [master, main]
    paths:
      - "tests/**"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Ensures only 1 workflow is running
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Test the playbooks (YAML) 
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3
        
      # Install the custom collection
      - name: Install collection 
        run: ansible-galaxy collection install git+https://github.com/powerops-mk/ansible-unifi-network.git

      # Run the playbook against the hosts
      - name: Apply playbook 
        run: ansible-playbook ./tests/*.yaml
